name: lidamas
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  flutter_bloc:
  flutter_screenutil:
  equatable:
  intl_phone_field: ^3.0.0
  pin_code_fields: ^7.3.0



  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^3.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/images/Vector (2).png


  fonts:
    - family: DIN Next LT Arabic
      fonts:
        - asset: assets/fonts/DINNextLTArabic-Bold-4.ttf
        - asset: assets/fonts/DINNextLTArabic-Heavy2-1.ttf
        - asset: assets/fonts/DINNEXTLTARABIC-LIGHT-2-2.ttf
        - asset: assets/fonts/DINNextLTArabic-Medium-4.ttf
        - asset: assets/fonts/DINNextLTArabic-Regular-3.ttf